# Generated by Django 4.2.1 on 2023-05-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddStud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Studid', models.IntegerField(null=True)),
                ('gpa', models.FloatField(null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('phoneNo', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('level', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('department', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
