# Generated by Django 4.1.7 on 2023-05-23 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddStud',
            new_name='Student',
        ),
    ]
