# Generated by Django 4.1.7 on 2023-05-23 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_student_id_alter_student_studid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Studid',
            new_name='id',
        ),
    ]
